# name: deploy-github
# on:
#   push:
#     paths:
#       - "client/**"
# jobs:
#   build-vue:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v3

#     - name: Install Node
#       uses: actions/setup-node@v3
#       with:
#         node-version: '14'

#     - name: Deploy
#       uses: JamesIves/github-pages-deploy-action@v4.3.0
#       with:
#         branch: github
#         folder: client/production
